// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function BindDirEntry(arg1:types.DirEntry):Promise<void>;

export function BindFileInfo(arg1:types.FileInfo):Promise<void>;
