// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BindDirEntry(arg1) {
  return window['go']['backend']['Backend']['BindDirEntry'](arg1);
}

export function BindFileInfo(arg1) {
  return window['go']['backend']['Backend']['BindFileInfo'](arg1);
}
